# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.notify_input import NotifyInput  # noqa: E501

class TestNotifyInput(unittest.TestCase):
    """NotifyInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotifyInput(self):
        """Test NotifyInput"""
        # inst = NotifyInput()

if __name__ == '__main__':
    unittest.main()
