# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.action_object import ActionObject  # noqa: E501

class TestActionObject(unittest.TestCase):
    """ActionObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionObject:
        """Test ActionObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionObject`
        """
        model = ActionObject()  # noqa: E501
        if include_optional:
            return ActionObject(
                deposits = None,
                into_account = None,
                of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                party = None,
                choose_between = [
                    openapi_client.models.bound.Bound(
                        from = 56, 
                        to = 56, )
                    ],
                for_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, ),
                notify_if = None,
                ref = ''
            )
        else:
            return ActionObject(
                deposits = None,
                into_account = None,
                of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                party = None,
                choose_between = [
                    openapi_client.models.bound.Bound(
                        from = 56, 
                        to = 56, )
                    ],
                for_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, ),
                notify_if = None,
                ref = '',
        )
        """

    def testActionObject(self):
        """Test ActionObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
