# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.contract_one_of3 import ContractOneOf3  # noqa: E501

class TestContractOneOf3(unittest.TestCase):
    """ContractOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractOneOf3:
        """Test ContractOneOf3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractOneOf3`
        """
        model = ContractOneOf3()  # noqa: E501
        if include_optional:
            return ContractOneOf3(
                be = None,
                let = '',
                then = None
            )
        else:
            return ContractOneOf3(
                be = None,
                let = '',
                then = None,
        )
        """

    def testContractOneOf3(self):
        """Test ContractOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
