# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.contracts_contract_id_transactions_post201_response_links import ContractsContractIdTransactionsPost201ResponseLinks  # noqa: E501

class TestContractsContractIdTransactionsPost201ResponseLinks(unittest.TestCase):
    """ContractsContractIdTransactionsPost201ResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractsContractIdTransactionsPost201ResponseLinks:
        """Test ContractsContractIdTransactionsPost201ResponseLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractsContractIdTransactionsPost201ResponseLinks`
        """
        model = ContractsContractIdTransactionsPost201ResponseLinks()  # noqa: E501
        if include_optional:
            return ContractsContractIdTransactionsPost201ResponseLinks(
                transaction = ''
            )
        else:
            return ContractsContractIdTransactionsPost201ResponseLinks(
        )
        """

    def testContractsContractIdTransactionsPost201ResponseLinks(self):
        """Test ContractsContractIdTransactionsPost201ResponseLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
