# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.withdraw_tx_body_envelope import WithdrawTxBodyEnvelope  # noqa: E501

class TestWithdrawTxBodyEnvelope(unittest.TestCase):
    """WithdrawTxBodyEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WithdrawTxBodyEnvelope:
        """Test WithdrawTxBodyEnvelope
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WithdrawTxBodyEnvelope`
        """
        model = WithdrawTxBodyEnvelope()  # noqa: E501
        if include_optional:
            return WithdrawTxBodyEnvelope(
                tx_body = openapi_client.models.text_envelope.TextEnvelope(
                    cbor_hex = '', 
                    description = '', 
                    type = '', ),
                withdrawal_id = '62ECB020842930cc01FFCCfeEe150AC32DcAEc8a83DDD7dBF7567C88195ffcea'
            )
        else:
            return WithdrawTxBodyEnvelope(
                tx_body = openapi_client.models.text_envelope.TextEnvelope(
                    cbor_hex = '', 
                    description = '', 
                    type = '', ),
                withdrawal_id = '62ECB020842930cc01FFCCfeEe150AC32DcAEc8a83DDD7dBF7567C88195ffcea',
        )
        """

    def testWithdrawTxBodyEnvelope(self):
        """Test WithdrawTxBodyEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
