# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.value_object_one_of8 import ValueObjectOneOf8  # noqa: E501

class TestValueObjectOneOf8(unittest.TestCase):
    """ValueObjectOneOf8 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValueObjectOneOf8:
        """Test ValueObjectOneOf8
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValueObjectOneOf8`
        """
        model = ValueObjectOneOf8()  # noqa: E501
        if include_optional:
            return ValueObjectOneOf8(
                ref = ''
            )
        else:
            return ValueObjectOneOf8(
                ref = '',
        )
        """

    def testValueObjectOneOf8(self):
        """Test ValueObjectOneOf8"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
