# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.value import Value  # noqa: E501

class TestValue(unittest.TestCase):
    """Value unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Value:
        """Test Value
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Value`
        """
        model = Value()  # noqa: E501
        if include_optional:
            return Value(
                amount_of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                in_account = None,
                negate = None,
                add = None,
                var_and = None,
                minus = None,
                value = None,
                multiply = None,
                times = None,
                by = None,
                divide = None,
                value_of_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, ),
                use_value = '',
                var_else = None,
                var_if = None,
                then = None
            )
        else:
            return Value(
                amount_of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                in_account = None,
                negate = None,
                add = None,
                var_and = None,
                minus = None,
                value = None,
                multiply = None,
                times = None,
                by = None,
                divide = None,
                value_of_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, ),
                use_value = '',
                var_else = None,
                var_if = None,
                then = None,
        )
        """

    def testValue(self):
        """Test Value"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
