# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.post_withdrawals_request import PostWithdrawalsRequest  # noqa: E501

class TestPostWithdrawalsRequest(unittest.TestCase):
    """PostWithdrawalsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWithdrawalsRequest:
        """Test PostWithdrawalsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWithdrawalsRequest`
        """
        model = PostWithdrawalsRequest()  # noqa: E501
        if include_optional:
            return PostWithdrawalsRequest(
                payouts = [
                    '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1'
                    ]
            )
        else:
            return PostWithdrawalsRequest(
                payouts = [
                    '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1'
                    ],
        )
        """

    def testPostWithdrawalsRequest(self):
        """Test PostWithdrawalsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
