# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.block_header import BlockHeader  # noqa: E501

class TestBlockHeader(unittest.TestCase):
    """BlockHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlockHeader:
        """Test BlockHeader
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlockHeader`
        """
        model = BlockHeader()  # noqa: E501
        if include_optional:
            return BlockHeader(
                block_header_hash = '',
                block_no = 0,
                slot_no = 0
            )
        else:
            return BlockHeader(
                block_header_hash = '',
                block_no = 0,
                slot_no = 0,
        )
        """

    def testBlockHeader(self):
        """Test BlockHeader"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
