# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_contract_response import GetContractResponse  # noqa: E501

class TestGetContractResponse(unittest.TestCase):
    """GetContractResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetContractResponse:
        """Test GetContractResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetContractResponse`
        """
        model = GetContractResponse()  # noqa: E501
        if include_optional:
            return GetContractResponse(
                links = openapi_client.models.get_contract_response_links.GetContractResponse_links(
                    transactions = '', ),
                resource = openapi_client.models.contract_state.ContractState(
                    assets = openapi_client.models.assets.Assets(
                        lovelace = 56, 
                        tokens = {
                            'key' : {
                                'key' : 56
                                }
                            }, ), 
                    block = openapi_client.models.block_header.BlockHeader(
                        block_header_hash = '', 
                        block_no = 0, 
                        slot_no = 0, ), 
                    continuations = '', 
                    contract_id = '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1', 
                    current_contract = null, 
                    initial_contract = null, 
                    metadata = {
                        'key' : null
                        }, 
                    role_token_minting_policy_id = '2ECB020842930cc01FFCCf', 
                    state = openapi_client.models.marlowe_state.MarloweState(
                        accounts = [
                            [
                                null
                                ]
                            ], 
                        bound_values = [
                            [
                                null
                                ]
                            ], 
                        choices = [
                            [
                                null
                                ]
                            ], 
                        min_time = 56, ), 
                    status = 'unsigned', 
                    tags = {
                        'key' : null
                        }, 
                    tx_body = openapi_client.models.text_envelope.TextEnvelope(
                        cbor_hex = '', 
                        description = '', 
                        type = '', ), 
                    unclaimed_payouts = [
                        openapi_client.models.payout.Payout(
                            assets = openapi_client.models.assets.Assets(
                                lovelace = 56, 
                                tokens = {
                                    'key' : {
                                        'key' : 56
                                        }
                                    }, ), 
                            payout_id = '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1', 
                            role = '', )
                        ], 
                    utxo = '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1', 
                    version = 'v1', )
            )
        else:
            return GetContractResponse(
                links = openapi_client.models.get_contract_response_links.GetContractResponse_links(
                    transactions = '', ),
                resource = openapi_client.models.contract_state.ContractState(
                    assets = openapi_client.models.assets.Assets(
                        lovelace = 56, 
                        tokens = {
                            'key' : {
                                'key' : 56
                                }
                            }, ), 
                    block = openapi_client.models.block_header.BlockHeader(
                        block_header_hash = '', 
                        block_no = 0, 
                        slot_no = 0, ), 
                    continuations = '', 
                    contract_id = '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1', 
                    current_contract = null, 
                    initial_contract = null, 
                    metadata = {
                        'key' : null
                        }, 
                    role_token_minting_policy_id = '2ECB020842930cc01FFCCf', 
                    state = openapi_client.models.marlowe_state.MarloweState(
                        accounts = [
                            [
                                null
                                ]
                            ], 
                        bound_values = [
                            [
                                null
                                ]
                            ], 
                        choices = [
                            [
                                null
                                ]
                            ], 
                        min_time = 56, ), 
                    status = 'unsigned', 
                    tags = {
                        'key' : null
                        }, 
                    tx_body = openapi_client.models.text_envelope.TextEnvelope(
                        cbor_hex = '', 
                        description = '', 
                        type = '', ), 
                    unclaimed_payouts = [
                        openapi_client.models.payout.Payout(
                            assets = openapi_client.models.assets.Assets(
                                lovelace = 56, 
                                tokens = {
                                    'key' : {
                                        'key' : 56
                                        }
                                    }, ), 
                            payout_id = '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1', 
                            role = '', )
                        ], 
                    utxo = '98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1', 
                    version = 'v1', ),
        )
        """

    def testGetContractResponse(self):
        """Test GetContractResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
