# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.tx_output_error import TxOutputError  # noqa: E501

class TestTxOutputError(unittest.TestCase):
    """TxOutputError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TxOutputError:
        """Test TxOutputError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TxOutputError`
        """
        model = TxOutputError()  # noqa: E501
        if include_optional:
            return TxOutputError(
                transaction_error = None
            )
        else:
            return TxOutputError(
                transaction_error = None,
        )
        """

    def testTxOutputError(self):
        """Test TxOutputError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
