# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.plutus_staking_credential_one_of1_staking_hash_inner import PlutusStakingCredentialOneOf1StakingHashInner  # noqa: E501

class TestPlutusStakingCredentialOneOf1StakingHashInner(unittest.TestCase):
    """PlutusStakingCredentialOneOf1StakingHashInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlutusStakingCredentialOneOf1StakingHashInner:
        """Test PlutusStakingCredentialOneOf1StakingHashInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlutusStakingCredentialOneOf1StakingHashInner`
        """
        model = PlutusStakingCredentialOneOf1StakingHashInner()  # noqa: E501
        if include_optional:
            return PlutusStakingCredentialOneOf1StakingHashInner(
            )
        else:
            return PlutusStakingCredentialOneOf1StakingHashInner(
        )
        """

    def testPlutusStakingCredentialOneOf1StakingHashInner(self):
        """Test PlutusStakingCredentialOneOf1StakingHashInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
