# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.contracts_post201_response_links import ContractsPost201ResponseLinks  # noqa: E501

class TestContractsPost201ResponseLinks(unittest.TestCase):
    """ContractsPost201ResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractsPost201ResponseLinks:
        """Test ContractsPost201ResponseLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractsPost201ResponseLinks`
        """
        model = ContractsPost201ResponseLinks()  # noqa: E501
        if include_optional:
            return ContractsPost201ResponseLinks(
                contract = ''
            )
        else:
            return ContractsPost201ResponseLinks(
        )
        """

    def testContractsPost201ResponseLinks(self):
        """Test ContractsPost201ResponseLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
