# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.interval_error import IntervalError  # noqa: E501

class TestIntervalError(unittest.TestCase):
    """IntervalError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntervalError:
        """Test IntervalError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntervalError`
        """
        model = IntervalError()  # noqa: E501
        if include_optional:
            return IntervalError(
                invalid_interval = openapi_client.models.invalid_interval_invalid_interval.InvalidInterval_invalidInterval(
                    from = 56, 
                    to = 56, ),
                interval_in_past_error = openapi_client.models.interval_in_past_interval_in_past_error.IntervalInPast_intervalInPastError(
                    from = 56, 
                    min_time = 56, 
                    to = 56, )
            )
        else:
            return IntervalError(
                invalid_interval = openapi_client.models.invalid_interval_invalid_interval.InvalidInterval_invalidInterval(
                    from = 56, 
                    to = 56, ),
                interval_in_past_error = openapi_client.models.interval_in_past_interval_in_past_error.IntervalInPast_intervalInPastError(
                    from = 56, 
                    min_time = 56, 
                    to = 56, ),
        )
        """

    def testIntervalError(self):
        """Test IntervalError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
