# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.party_role_name import PartyRoleName  # noqa: E501

class TestPartyRoleName(unittest.TestCase):
    """PartyRoleName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PartyRoleName:
        """Test PartyRoleName
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PartyRoleName`
        """
        model = PartyRoleName()  # noqa: E501
        if include_optional:
            return PartyRoleName(
                role_token = ''
            )
        else:
            return PartyRoleName(
                role_token = '',
        )
        """

    def testPartyRoleName(self):
        """Test PartyRoleName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
