# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.withdrawals_post201_response import WithdrawalsPost201Response  # noqa: E501

class TestWithdrawalsPost201Response(unittest.TestCase):
    """WithdrawalsPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WithdrawalsPost201Response:
        """Test WithdrawalsPost201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WithdrawalsPost201Response`
        """
        model = WithdrawalsPost201Response()  # noqa: E501
        if include_optional:
            return WithdrawalsPost201Response(
                links = openapi_client.models._withdrawals_post_201_response_links._withdrawals_post_201_response_links(
                    withdrawal = '', ),
                resource = openapi_client.models.apply_inputs_tx_envelope.ApplyInputsTxEnvelope(
                    tx = openapi_client.models.text_envelope.TextEnvelope(
                        cbor_hex = '', 
                        description = '', 
                        type = '', ), 
                    withdrawal_id = '62ECB020842930cc01FFCCfeEe150AC32DcAEc8a83DDD7dBF7567C88195ffcea', )
            )
        else:
            return WithdrawalsPost201Response(
                links = openapi_client.models._withdrawals_post_201_response_links._withdrawals_post_201_response_links(
                    withdrawal = '', ),
                resource = openapi_client.models.apply_inputs_tx_envelope.ApplyInputsTxEnvelope(
                    tx = openapi_client.models.text_envelope.TextEnvelope(
                        cbor_hex = '', 
                        description = '', 
                        type = '', ), 
                    withdrawal_id = '62ECB020842930cc01FFCCfeEe150AC32DcAEc8a83DDD7dBF7567C88195ffcea', ),
        )
        """

    def testWithdrawalsPost201Response(self):
        """Test WithdrawalsPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
