# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.labelled_object_value import LabelledObjectValue  # noqa: E501

class TestLabelledObjectValue(unittest.TestCase):
    """LabelledObjectValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LabelledObjectValue:
        """Test LabelledObjectValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LabelledObjectValue`
        """
        model = LabelledObjectValue()  # noqa: E501
        if include_optional:
            return LabelledObjectValue(
                amount_of_token = None,
                in_account = None,
                negate = None,
                add = None,
                var_and = None,
                minus = None,
                value = None,
                multiply = None,
                times = None,
                by = None,
                divide = None,
                value_of_choice = openapi_client.models.choice_id_object.ChoiceIdObject(
                    choice_name = '', 
                    choice_owner = null, ),
                use_value = '',
                var_else = None,
                var_if = None,
                then = None,
                ref = '',
                both = None,
                either = None,
                var_or = None,
                var_not = None,
                chose_something_for = openapi_client.models.choice_id_object.ChoiceIdObject(
                    choice_name = '', 
                    choice_owner = null, ),
                ge_than = None,
                gt = None,
                lt = None,
                le_than = None,
                equal_to = None,
                from_account = None,
                pay = None,
                to = None,
                token = None,
                timeout = 56,
                timeout_continuation = None,
                when = [
                    null
                    ],
                be = None,
                let = '',
                var_assert = None,
                role_token = '',
                address = 'addr1w94f8ywk4fg672xasahtk4t9k6w3aql943uxz5rt62d4dvq8evxaf',
                currency_symbol = '',
                token_name = '',
                deposits = None,
                into_account = None,
                of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                party = None,
                choose_between = [
                    openapi_client.models.bound.Bound(
                        from = 56, 
                        to = 56, )
                    ],
                for_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, ),
                notify_if = None
            )
        else:
            return LabelledObjectValue(
                amount_of_token = None,
                in_account = None,
                negate = None,
                add = None,
                var_and = None,
                minus = None,
                value = None,
                multiply = None,
                times = None,
                by = None,
                divide = None,
                value_of_choice = openapi_client.models.choice_id_object.ChoiceIdObject(
                    choice_name = '', 
                    choice_owner = null, ),
                use_value = '',
                var_else = None,
                var_if = None,
                then = None,
                ref = '',
                both = None,
                either = None,
                var_or = None,
                var_not = None,
                chose_something_for = openapi_client.models.choice_id_object.ChoiceIdObject(
                    choice_name = '', 
                    choice_owner = null, ),
                ge_than = None,
                gt = None,
                lt = None,
                le_than = None,
                equal_to = None,
                from_account = None,
                pay = None,
                to = None,
                token = None,
                timeout = 56,
                timeout_continuation = None,
                when = [
                    null
                    ],
                be = None,
                let = '',
                var_assert = None,
                role_token = '',
                address = 'addr1w94f8ywk4fg672xasahtk4t9k6w3aql943uxz5rt62d4dvq8evxaf',
                currency_symbol = '',
                token_name = '',
                deposits = None,
                into_account = None,
                of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                party = None,
                choose_between = [
                    openapi_client.models.bound.Bound(
                        from = 56, 
                        to = 56, )
                    ],
                for_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, ),
                notify_if = None,
        )
        """

    def testLabelledObjectValue(self):
        """Test LabelledObjectValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
