# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.marlowe_state import MarloweState  # noqa: E501

class TestMarloweState(unittest.TestCase):
    """MarloweState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarloweState:
        """Test MarloweState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarloweState`
        """
        model = MarloweState()  # noqa: E501
        if include_optional:
            return MarloweState(
                accounts = [
                    [
                        null
                        ]
                    ],
                bound_values = [
                    [
                        null
                        ]
                    ],
                choices = [
                    [
                        null
                        ]
                    ],
                min_time = 56
            )
        else:
            return MarloweState(
                accounts = [
                    [
                        null
                        ]
                    ],
                bound_values = [
                    [
                        null
                        ]
                    ],
                choices = [
                    [
                        null
                        ]
                    ],
                min_time = 56,
        )
        """

    def testMarloweState(self):
        """Test MarloweState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
