# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.labelled_object import LabelledObject  # noqa: E501

class TestLabelledObject(unittest.TestCase):
    """LabelledObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LabelledObject:
        """Test LabelledObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LabelledObject`
        """
        model = LabelledObject()  # noqa: E501
        if include_optional:
            return LabelledObject(
                label = '',
                type = 'value',
                value = None
            )
        else:
            return LabelledObject(
                label = '',
                type = 'value',
                value = None,
        )
        """

    def testLabelledObject(self):
        """Test LabelledObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
