# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.deposit_continuation_input import DepositContinuationInput  # noqa: E501

class TestDepositContinuationInput(unittest.TestCase):
    """DepositContinuationInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepositContinuationInput:
        """Test DepositContinuationInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepositContinuationInput`
        """
        model = DepositContinuationInput()  # noqa: E501
        if include_optional:
            return DepositContinuationInput(
                continuation_hash = '',
                input_from_party = None,
                into_account = None,
                merkleized_continuation = None,
                of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                that_deposits = 56
            )
        else:
            return DepositContinuationInput(
                continuation_hash = '',
                input_from_party = None,
                into_account = None,
                merkleized_continuation = None,
                of_token = openapi_client.models.token.Token(
                    currency_symbol = '', 
                    token_name = '', ),
                that_deposits = 56,
        )
        """

    def testDepositContinuationInput(self):
        """Test DepositContinuationInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
