# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.choice_action_object import ChoiceActionObject  # noqa: E501

class TestChoiceActionObject(unittest.TestCase):
    """ChoiceActionObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChoiceActionObject:
        """Test ChoiceActionObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChoiceActionObject`
        """
        model = ChoiceActionObject()  # noqa: E501
        if include_optional:
            return ChoiceActionObject(
                choose_between = [
                    openapi_client.models.bound.Bound(
                        from = 56, 
                        to = 56, )
                    ],
                for_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, )
            )
        else:
            return ChoiceActionObject(
                choose_between = [
                    openapi_client.models.bound.Bound(
                        from = 56, 
                        to = 56, )
                    ],
                for_choice = openapi_client.models.choice_id.ChoiceId(
                    choice_name = '', 
                    choice_owner = null, ),
        )
        """

    def testChoiceActionObject(self):
        """Test ChoiceActionObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
