# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.value_one_of5 import ValueOneOf5  # noqa: E501

class TestValueOneOf5(unittest.TestCase):
    """ValueOneOf5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValueOneOf5:
        """Test ValueOneOf5
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValueOneOf5`
        """
        model = ValueOneOf5()  # noqa: E501
        if include_optional:
            return ValueOneOf5(
                by = None,
                divide = None
            )
        else:
            return ValueOneOf5(
                by = None,
                divide = None,
        )
        """

    def testValueOneOf5(self):
        """Test ValueOneOf5"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
