# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.withdrawals_post201_response_links import WithdrawalsPost201ResponseLinks  # noqa: E501

class TestWithdrawalsPost201ResponseLinks(unittest.TestCase):
    """WithdrawalsPost201ResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WithdrawalsPost201ResponseLinks:
        """Test WithdrawalsPost201ResponseLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WithdrawalsPost201ResponseLinks`
        """
        model = WithdrawalsPost201ResponseLinks()  # noqa: E501
        if include_optional:
            return WithdrawalsPost201ResponseLinks(
                withdrawal = ''
            )
        else:
            return WithdrawalsPost201ResponseLinks(
        )
        """

    def testWithdrawalsPost201ResponseLinks(self):
        """Test WithdrawalsPost201ResponseLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
