# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.payouts_payout_id_get200_response_links import PayoutsPayoutIdGet200ResponseLinks  # noqa: E501

class TestPayoutsPayoutIdGet200ResponseLinks(unittest.TestCase):
    """PayoutsPayoutIdGet200ResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayoutsPayoutIdGet200ResponseLinks:
        """Test PayoutsPayoutIdGet200ResponseLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayoutsPayoutIdGet200ResponseLinks`
        """
        model = PayoutsPayoutIdGet200ResponseLinks()  # noqa: E501
        if include_optional:
            return PayoutsPayoutIdGet200ResponseLinks(
                contract = '',
                transaction = '',
                withdrawal = ''
            )
        else:
            return PayoutsPayoutIdGet200ResponseLinks(
        )
        """

    def testPayoutsPayoutIdGet200ResponseLinks(self):
        """Test PayoutsPayoutIdGet200ResponseLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
