# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AssertFail(str, Enum):
    """
    A semantics assertion failed.
    """

    """
    allowed enum values
    """
    ASSERTION_FAILED = 'assertion_failed'

    @classmethod
    def from_json(cls, json_str: str) -> AssertFail:
        """Create an instance of AssertFail from a JSON string"""
        return AssertFail(json.loads(json_str))


