# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, conint

class BlockHeader(BaseModel):
    """
    BlockHeader
    """
    block_header_hash: StrictStr = Field(..., alias="blockHeaderHash")
    block_no: conint(strict=True, le=9223372036854775807, ge=0) = Field(..., alias="blockNo")
    slot_no: conint(strict=True, le=9223372036854775807, ge=0) = Field(..., alias="slotNo")
    __properties = ["blockHeaderHash", "blockNo", "slotNo"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BlockHeader:
        """Create an instance of BlockHeader from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BlockHeader:
        """Create an instance of BlockHeader from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BlockHeader.parse_obj(obj)

        _obj = BlockHeader.parse_obj({
            "block_header_hash": obj.get("blockHeaderHash"),
            "block_no": obj.get("blockNo"),
            "slot_no": obj.get("slotNo")
        })
        return _obj


