# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.contract_state import ContractState
from openapi_client.models.contracts_contract_id_get200_response_links import ContractsContractIdGet200ResponseLinks

class ContractsContractIdGet200Response(BaseModel):
    """
    ContractsContractIdGet200Response
    """
    links: ContractsContractIdGet200ResponseLinks = Field(...)
    resource: ContractState = Field(...)
    __properties = ["links", "resource"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ContractsContractIdGet200Response:
        """Create an instance of ContractsContractIdGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resource
        if self.resource:
            _dict['resource'] = self.resource.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ContractsContractIdGet200Response:
        """Create an instance of ContractsContractIdGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ContractsContractIdGet200Response.parse_obj(obj)

        _obj = ContractsContractIdGet200Response.parse_obj({
            "links": ContractsContractIdGet200ResponseLinks.from_dict(obj.get("links")) if obj.get("links") is not None else None,
            "resource": ContractState.from_dict(obj.get("resource")) if obj.get("resource") is not None else None
        })
        return _obj


