# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class ContractsContractIdGet200ResponseLinks(BaseModel):
    """
    ContractsContractIdGet200ResponseLinks
    """
    transactions: Optional[StrictStr] = None
    __properties = ["transactions"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ContractsContractIdGet200ResponseLinks:
        """Create an instance of ContractsContractIdGet200ResponseLinks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ContractsContractIdGet200ResponseLinks:
        """Create an instance of ContractsContractIdGet200ResponseLinks from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ContractsContractIdGet200ResponseLinks.parse_obj(obj)

        _obj = ContractsContractIdGet200ResponseLinks.parse_obj({
            "transactions": obj.get("transactions")
        })
        return _obj


