# coding: utf-8

"""
    Marlowe Runtime REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from openapi_client.models.party import Party
from openapi_client.models.payee import Payee
from openapi_client.models.token import Token
from openapi_client.models.value import Value
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ContractOneOf(BaseModel):
    """
    A payment will be sent from an account to a payee.
    """ # noqa: E501
    from_account: Party
    pay: Value
    then: Contract
    to: Payee
    token: Token
    __properties: ClassVar[List[str]] = ["from_account", "pay", "then", "to", "token"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContractOneOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of from_account
        if self.from_account:
            _dict['from_account'] = self.from_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pay
        if self.pay:
            _dict['pay'] = self.pay.to_dict()
        # override the default output from pydantic by calling `to_dict()` of then
        if self.then:
            _dict['then'] = self.then.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to
        if self.to:
            _dict['to'] = self.to.to_dict()
        # override the default output from pydantic by calling `to_dict()` of token
        if self.token:
            _dict['token'] = self.token.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ContractOneOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from_account": Party.from_dict(obj.get("from_account")) if obj.get("from_account") is not None else None,
            "pay": Value.from_dict(obj.get("pay")) if obj.get("pay") is not None else None,
            "then": Contract.from_dict(obj.get("then")) if obj.get("then") is not None else None,
            "to": Payee.from_dict(obj.get("to")) if obj.get("to") is not None else None,
            "token": Token.from_dict(obj.get("token")) if obj.get("token") is not None else None
        })
        return _obj

from openapi_client.models.contract import Contract
# TODO: Rewrite to not use raise_errors
ContractOneOf.model_rebuild(raise_errors=False)

