# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field

class IfValue(BaseModel):
    """
    IfValue
    """
    var_else: Value = Field(..., alias="else")
    var_if: Observation = Field(..., alias="if")
    then: Value = Field(...)
    __properties = ["else", "if", "then"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IfValue:
        """Create an instance of IfValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of var_else
        if self.var_else:
            _dict['else'] = self.var_else.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_if
        if self.var_if:
            _dict['if'] = self.var_if.to_dict()
        # override the default output from pydantic by calling `to_dict()` of then
        if self.then:
            _dict['then'] = self.then.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IfValue:
        """Create an instance of IfValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IfValue.parse_obj(obj)

        _obj = IfValue.parse_obj({
            "var_else": Value.from_dict(obj.get("else")) if obj.get("else") is not None else None,
            "var_if": Observation.from_dict(obj.get("if")) if obj.get("if") is not None else None,
            "then": Value.from_dict(obj.get("then")) if obj.get("then") is not None else None
        })
        return _obj

from openapi_client.models.observation import Observation
from openapi_client.models.value import Value
IfValue.update_forward_refs()

