# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from openapi_client.models.input_one_of import InputOneOf
from openapi_client.models.input_one_of1 import InputOneOf1
from openapi_client.models.input_one_of2 import InputOneOf2
from openapi_client.models.input_one_of3 import InputOneOf3
from openapi_client.models.input_one_of4 import InputOneOf4
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

INPUT_ONE_OF_SCHEMAS = ["InputOneOf", "InputOneOf1", "InputOneOf2", "InputOneOf3", "InputOneOf4", "str"]

class Input(BaseModel):
    """
    An input to a Marlowe transaction
    """
    # data type: InputOneOf
    oneof_schema_1_validator: Optional[InputOneOf] = None
    # data type: str
    oneof_schema_2_validator: Optional[StrictStr] = Field(None, description="Notify a contract to check a condition")
    # data type: InputOneOf1
    oneof_schema_3_validator: Optional[InputOneOf1] = None
    # data type: InputOneOf2
    oneof_schema_4_validator: Optional[InputOneOf2] = None
    # data type: InputOneOf3
    oneof_schema_5_validator: Optional[InputOneOf3] = None
    # data type: InputOneOf4
    oneof_schema_6_validator: Optional[InputOneOf4] = None
    if TYPE_CHECKING:
        actual_instance: Union[InputOneOf, InputOneOf1, InputOneOf2, InputOneOf3, InputOneOf4, str]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(INPUT_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Input.construct()
        error_messages = []
        match = 0
        # validate data type: InputOneOf
        if not isinstance(v, InputOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InputOneOf`")
        else:
            match += 1
        # validate data type: str
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: InputOneOf1
        if not isinstance(v, InputOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InputOneOf1`")
        else:
            match += 1
        # validate data type: InputOneOf2
        if not isinstance(v, InputOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InputOneOf2`")
        else:
            match += 1
        # validate data type: InputOneOf3
        if not isinstance(v, InputOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InputOneOf3`")
        else:
            match += 1
        # validate data type: InputOneOf4
        if not isinstance(v, InputOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InputOneOf4`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Input with oneOf schemas: InputOneOf, InputOneOf1, InputOneOf2, InputOneOf3, InputOneOf4, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Input with oneOf schemas: InputOneOf, InputOneOf1, InputOneOf2, InputOneOf3, InputOneOf4, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Input:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Input:
        """Returns the object represented by the json string"""
        instance = Input.construct()
        error_messages = []
        match = 0

        # deserialize data into InputOneOf
        try:
            instance.actual_instance = InputOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InputOneOf1
        try:
            instance.actual_instance = InputOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InputOneOf2
        try:
            instance.actual_instance = InputOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InputOneOf3
        try:
            instance.actual_instance = InputOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InputOneOf4
        try:
            instance.actual_instance = InputOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Input with oneOf schemas: InputOneOf, InputOneOf1, InputOneOf2, InputOneOf3, InputOneOf4, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Input with oneOf schemas: InputOneOf, InputOneOf1, InputOneOf2, InputOneOf3, InputOneOf4, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


