# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt
from openapi_client.models.choice_id import ChoiceId

class InputOneOf2(BaseModel):
    """
    Make a choice in a contract  # noqa: E501
    """
    for_choice_id: ChoiceId = Field(...)
    input_that_chooses_num: StrictInt = Field(...)
    __properties = ["for_choice_id", "input_that_chooses_num"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InputOneOf2:
        """Create an instance of InputOneOf2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of for_choice_id
        if self.for_choice_id:
            _dict['for_choice_id'] = self.for_choice_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InputOneOf2:
        """Create an instance of InputOneOf2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InputOneOf2.parse_obj(obj)

        _obj = InputOneOf2.parse_obj({
            "for_choice_id": ChoiceId.from_dict(obj.get("for_choice_id")) if obj.get("for_choice_id") is not None else None,
            "input_that_chooses_num": obj.get("input_that_chooses_num")
        })
        return _obj


