# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.interval_error_one_of1_interval_in_past_error import IntervalErrorOneOf1IntervalInPastError

class IntervalErrorOneOf1(BaseModel):
    """
    Marlowe transaction interval in past.  # noqa: E501
    """
    interval_in_past_error: IntervalErrorOneOf1IntervalInPastError = Field(..., alias="intervalInPastError")
    __properties = ["intervalInPastError"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IntervalErrorOneOf1:
        """Create an instance of IntervalErrorOneOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of interval_in_past_error
        if self.interval_in_past_error:
            _dict['intervalInPastError'] = self.interval_in_past_error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IntervalErrorOneOf1:
        """Create an instance of IntervalErrorOneOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IntervalErrorOneOf1.parse_obj(obj)

        _obj = IntervalErrorOneOf1.parse_obj({
            "interval_in_past_error": IntervalErrorOneOf1IntervalInPastError.from_dict(obj.get("intervalInPastError")) if obj.get("intervalInPastError") is not None else None
        })
        return _obj


