# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class NotifyInput(str, Enum):
    """
    Notify a contract to check a condition
    """

    """
    allowed enum values
    """
    INPUT_NOTIFY = 'input_notify'

    @classmethod
    def from_json(cls, json_str: str) -> NotifyInput:
        """Create an instance of NotifyInput from a JSON string"""
        return NotifyInput(json.loads(json_str))


