# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.choice_id_object import ChoiceIdObject

class ObservationObjectOneOf3(BaseModel):
    """
    ObservationObjectOneOf3
    """
    chose_something_for: ChoiceIdObject = Field(...)
    __properties = ["chose_something_for"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ObservationObjectOneOf3:
        """Create an instance of ObservationObjectOneOf3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of chose_something_for
        if self.chose_something_for:
            _dict['chose_something_for'] = self.chose_something_for.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ObservationObjectOneOf3:
        """Create an instance of ObservationObjectOneOf3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ObservationObjectOneOf3.parse_obj(obj)

        _obj = ObservationObjectOneOf3.parse_obj({
            "chose_something_for": ChoiceIdObject.from_dict(obj.get("chose_something_for")) if obj.get("chose_something_for") is not None else None
        })
        return _obj


