# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.party import Party

class PayeeOneOf(BaseModel):
    """
    Pays funds into a party's account in the contract.  # noqa: E501
    """
    account: Party = Field(...)
    __properties = ["account"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PayeeOneOf:
        """Create an instance of PayeeOneOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PayeeOneOf:
        """Create an instance of PayeeOneOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PayeeOneOf.parse_obj(obj)

        _obj = PayeeOneOf.parse_obj({
            "account": Party.from_dict(obj.get("account")) if obj.get("account") is not None else None
        })
        return _obj


