# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.party_object import PartyObject

class PayeeObjectOneOf1(BaseModel):
    """
    Pays funds to a party.  # noqa: E501
    """
    party: PartyObject = Field(...)
    __properties = ["party"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PayeeObjectOneOf1:
        """Create an instance of PayeeObjectOneOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of party
        if self.party:
            _dict['party'] = self.party.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PayeeObjectOneOf1:
        """Create an instance of PayeeObjectOneOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PayeeObjectOneOf1.parse_obj(obj)

        _obj = PayeeObjectOneOf1.parse_obj({
            "party": PartyObject.from_dict(obj.get("party")) if obj.get("party") is not None else None
        })
        return _obj


