# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, conlist

class PlutusStakingCredentialOneOf1(BaseModel):
    """
    A Plutus staking pointer.  # noqa: E501
    """
    staking_hash: conlist(StrictInt, max_items=3, min_items=3) = Field(..., alias="stakingHash")
    __properties = ["stakingHash"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlutusStakingCredentialOneOf1:
        """Create an instance of PlutusStakingCredentialOneOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlutusStakingCredentialOneOf1:
        """Create an instance of PlutusStakingCredentialOneOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlutusStakingCredentialOneOf1.parse_obj(obj)

        _obj = PlutusStakingCredentialOneOf1.parse_obj({
            "staking_hash": obj.get("stakingHash")
        })
        return _obj


