# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.plutus_credential import PlutusCredential

class StakingHash(BaseModel):
    """
    A Plutus staking hash.  # noqa: E501
    """
    staking_hash: PlutusCredential = Field(..., alias="stakingHash")
    __properties = ["stakingHash"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StakingHash:
        """Create an instance of StakingHash from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of staking_hash
        if self.staking_hash:
            _dict['stakingHash'] = self.staking_hash.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StakingHash:
        """Create an instance of StakingHash from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StakingHash.parse_obj(obj)

        _obj = StakingHash.parse_obj({
            "staking_hash": PlutusCredential.from_dict(obj.get("stakingHash")) if obj.get("stakingHash") is not None else None
        })
        return _obj


