# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, validator
from openapi_client.models.interval_error import IntervalError

class TransactionErrorOneOf(BaseModel):
    """
    An invalid time interval.  # noqa: E501
    """
    context: IntervalError = Field(...)
    error: StrictStr = Field(...)
    __properties = ["context", "error"]

    @validator('error')
    def error_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('TEIntervalError'):
            raise ValueError("must be one of enum values ('TEIntervalError')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TransactionErrorOneOf:
        """Create an instance of TransactionErrorOneOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['context'] = self.context.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TransactionErrorOneOf:
        """Create an instance of TransactionErrorOneOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TransactionErrorOneOf.parse_obj(obj)

        _obj = TransactionErrorOneOf.parse_obj({
            "context": IntervalError.from_dict(obj.get("context")) if obj.get("context") is not None else None,
            "error": obj.get("error")
        })
        return _obj


