# coding: utf-8

"""
    Marlowe Runtime REST API

    REST API for Marlowe Runtime

    The version of the OpenAPI document: 0.0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.transaction_error import TransactionError

class TransactionOutputOneOf1(BaseModel):
    """
    Marlowe transaction error.  # noqa: E501
    """
    transaction_error: TransactionError = Field(...)
    __properties = ["transaction_error"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TransactionOutputOneOf1:
        """Create an instance of TransactionOutputOneOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of transaction_error
        if self.transaction_error:
            _dict['transaction_error'] = self.transaction_error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TransactionOutputOneOf1:
        """Create an instance of TransactionOutputOneOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TransactionOutputOneOf1.parse_obj(obj)

        _obj = TransactionOutputOneOf1.parse_obj({
            "transaction_error": TransactionError.from_dict(obj.get("transaction_error")) if obj.get("transaction_error") is not None else None
        })
        return _obj


