# coding: utf-8

"""
    Marlowe Runtime REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from pydantic import Field
from openapi_client.models.transaction_warning_one_of import TransactionWarningOneOf
from openapi_client.models.transaction_warning_one_of1 import TransactionWarningOneOf1
from openapi_client.models.transaction_warning_one_of2 import TransactionWarningOneOf2
from openapi_client.models.transaction_warning_one_of3 import TransactionWarningOneOf3
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

TRANSACTIONWARNING_ONE_OF_SCHEMAS = ["TransactionWarningOneOf", "TransactionWarningOneOf1", "TransactionWarningOneOf2", "TransactionWarningOneOf3", "str"]

class TransactionWarning(BaseModel):
    """
    A transaction semantics warning.
    """
    # data type: TransactionWarningOneOf
    oneof_schema_1_validator: Optional[TransactionWarningOneOf] = None
    # data type: TransactionWarningOneOf1
    oneof_schema_2_validator: Optional[TransactionWarningOneOf1] = None
    # data type: TransactionWarningOneOf2
    oneof_schema_3_validator: Optional[TransactionWarningOneOf2] = None
    # data type: TransactionWarningOneOf3
    oneof_schema_4_validator: Optional[TransactionWarningOneOf3] = None
    # data type: str
    oneof_schema_5_validator: Optional[StrictStr] = Field(default=None, description="A semantics assertion failed.")
    actual_instance: Optional[Union[TransactionWarningOneOf, TransactionWarningOneOf1, TransactionWarningOneOf2, TransactionWarningOneOf3, str]] = None
    one_of_schemas: List[str] = Literal["TransactionWarningOneOf", "TransactionWarningOneOf1", "TransactionWarningOneOf2", "TransactionWarningOneOf3", "str"]

    model_config = {
        "validate_assignment": True
    }


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = TransactionWarning.model_construct()
        error_messages = []
        match = 0
        # validate data type: TransactionWarningOneOf
        if not isinstance(v, TransactionWarningOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TransactionWarningOneOf`")
        else:
            match += 1
        # validate data type: TransactionWarningOneOf1
        if not isinstance(v, TransactionWarningOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TransactionWarningOneOf1`")
        else:
            match += 1
        # validate data type: TransactionWarningOneOf2
        if not isinstance(v, TransactionWarningOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TransactionWarningOneOf2`")
        else:
            match += 1
        # validate data type: TransactionWarningOneOf3
        if not isinstance(v, TransactionWarningOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TransactionWarningOneOf3`")
        else:
            match += 1
        # validate data type: str
        try:
            instance.oneof_schema_5_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in TransactionWarning with oneOf schemas: TransactionWarningOneOf, TransactionWarningOneOf1, TransactionWarningOneOf2, TransactionWarningOneOf3, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in TransactionWarning with oneOf schemas: TransactionWarningOneOf, TransactionWarningOneOf1, TransactionWarningOneOf2, TransactionWarningOneOf3, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into TransactionWarningOneOf
        try:
            instance.actual_instance = TransactionWarningOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TransactionWarningOneOf1
        try:
            instance.actual_instance = TransactionWarningOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TransactionWarningOneOf2
        try:
            instance.actual_instance = TransactionWarningOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TransactionWarningOneOf3
        try:
            instance.actual_instance = TransactionWarningOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_5_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_5_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into TransactionWarning with oneOf schemas: TransactionWarningOneOf, TransactionWarningOneOf1, TransactionWarningOneOf2, TransactionWarningOneOf3, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TransactionWarning with oneOf schemas: TransactionWarningOneOf, TransactionWarningOneOf1, TransactionWarningOneOf2, TransactionWarningOneOf3, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


