# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TxStatus(str, Enum):
    """
    The status of a transaction on the local node.
    """

    """
    allowed enum values
    """
    UNSIGNED = 'unsigned'
    SUBMITTED = 'submitted'
    CONFIRMED = 'confirmed'

    @classmethod
    def from_json(cls, json_str: str) -> TxStatus:
        """Create an instance of TxStatus from a JSON string"""
        return TxStatus(json.loads(json_str))


