# coding: utf-8

"""
    Marlowe Runtime REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TxStatus(str, Enum):
    """
    The status of a transaction on the local node.
    """

    """
    allowed enum values
    """
    UNSIGNED = 'unsigned'
    SUBMITTED = 'submitted'
    CONFIRMED = 'confirmed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TxStatus from a JSON string"""
        return cls(json.loads(json_str))


