name: Automatically create python code to interact with the API
on: push

env:
  FILE_PATH: openapi.json

jobs:
  run:
    name: Generate code python to interact with the API described in openapi.json
    runs-on: ubuntu-latest
    steps:
      - name: Set file path
        run: echo "FILE_PATH=openapi.json" >> "$GITHUB_ENV"

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Check if running the action is needed.
        run: echo "API_SPECS_CHANGED=$(git diff --name-only HEAD HEAD~1 | grep $FILE_PATH)" >> "$GITHUB_ENV"

      - name: Show variables
        run: echo "HI $API_SPECS_CHANGED $FILE_PATH"

      - name: Set up Node.js
        uses: actions/setup-node@v3
      
      - name: Remove previously generated code
        run: xargs rm -r < .openapi-generator/FILES

      - name: Generate python code from specs
        run: npx @openapitools/openapi-generator-cli generate -i $FILE_PATH -g python

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
